[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile.ultra-light"

[deploy]
startCommand = "gunicorn --bind 0.0.0.0:$PORT --workers 1 --timeout 60 --max-requests 500 app:app"
healthcheckPath = "/health"
healthcheckTimeout = 180
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5

[env]
FLASK_ENV = "production"
PYTHONUNBUFFERED = "1"
TF_CPP_MIN_LOG_LEVEL = "3"
TF_ENABLE_ONEDNN_OPTS = "0"
OMP_NUM_THREADS = "1"
