[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile.railway"

[deploy]
startCommand = "gunicorn --bind 0.0.0.0:$PORT --workers 1 --timeout 120 --max-requests 1000 app:app"
healthcheckPath = "/health/live"
healthcheckTimeout = 30
healthcheckInterval = 15
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[env]
FLASK_ENV = "production"
PYTHONUNBUFFERED = "1"
TF_CPP_MIN_LOG_LEVEL = "3"
