[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile.railway"

[deploy]
startCommand = "gunicorn --bind 0.0.0.0:$PORT --workers 2 --timeout 120 --max-requests 1000 app:app"
healthcheckPath = "/health"
healthcheckTimeout = 60
healthcheckInterval = 30
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5

[env]
FLASK_ENV = "production"
PYTHONUNBUFFERED = "1"
TF_CPP_MIN_LOG_LEVEL = "3"
TF_ENABLE_ONEDNN_OPTS = "0"
